image_finetune: false

output_dir: "outputs_single_flow_gen"
pretrained_model_path: "models/StableDiffusion-FlowGen/"
vae_pretrained_path: "vae_kl_outputs/bs4x64_accum4_max150_320x512-2023-11-07T16-11-18/checkpoints/checkpoint200000.ckpt"
unet_checkpoint_path: "./SD15_inchannel8.ckpt"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  sample_size:     [320, 512]
  max_sample_stride:  90
  sample_n_frames: 1

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "."

learning_rate:    3.e-5
train_batch_size: 1

max_train_epoch:      -1
max_train_steps:      1000000
checkpointing_epochs: -1
checkpointing_steps:  20000

validation_steps:       500000000
validation_steps_tuple: [200000000000, 500000000000]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: false

is_debug: False
