image_finetune: false

output_dir: "outputs_flow_gen"
pretrained_model_path: "models/StableDiffusion-FlowGen/"
vae_pretrained_path: "pretrained_ckpt/vae_kl_outputs/bs4x64_accum4_max150_320x512-2023-11-07T16-11-18/checkpoints/checkpoint200000.ckpt"
pretrained_singel_model_path: "pretrained_ckpt/outputs_single_flow_gen/vaepre20w_bs1x64_accum1_max90_320x512-2023-11-18T02-48-21/checkpoints/checkpoint80000.ckpt"
pretrained_motion_module_path: "models/Motion_Module/mm_sd_v15_v2.ckpt"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  motion_module_mid_block: true
  use_inflated_groupnorm: true

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  sample_size:     [320, 320]
  sample_stride:  8
  sample_n_frames: 16

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    3.e-5
train_batch_size: 2

max_train_epoch:      -1
max_train_steps:      10000000
checkpointing_epochs: -1
checkpointing_steps:  10000

validation_steps:       500000000
validation_steps_tuple: [200000000000, 500000000000]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: false

is_debug: False
