image_finetune: false

output_dir: "vae_kl_outputs"
pretrained_model_path: "models/StableDiffusion-FlowGen/"

#vae_pretrained_path : "vae_kl_outputs/vae_training-2023-10-17T23-22-05/checkpoints/checkpoint100000.ckpt"

train_data:
  sample_size:     [320, 512]
  max_sample_stride:  150
  sample_n_frames: 1

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 25
  guidance_scale: 8.

learning_rate:    1.e-5
train_batch_size: 4
gradient_accumulation_steps: 4

max_train_epoch:      -1
max_train_steps:      1000000
checkpointing_epochs: -1
checkpointing_steps:  10000

validation_steps:       500000000
validation_steps_tuple: [200000000000, 500000000000]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False
